@startuml
(*) -->"用户填写注册信息"
--> "检查输入"
If "输入合法" then
--> [Yes] "判断用户名是否存在"
    If "用户名存在" then
        --> [Yes] "用户填写注册信息"
    Else
        --> [No] 向表中插入用户信息
        --> "完成注册"
        -->(*)
    Endif
else
--> [No] "用户填写注册信息"
Endif
@enduml