@startuml
(*)  --> "用户创建收藏夹"
If "收藏夹是否重名" then
--> [重名] "提示无法添加"
-->"请重新输入收藏夹名字"
-->"用户创建收藏夹"
else
--> "添加成功"
Endif
-->(*)
(*)  --> "用户删除收藏夹"
If "收藏夹是否存在" then
--> [不存在] "删除失败"
else
--> "删除成功"
Endif
-->(*)
@enduml