@startuml
(*)  --> "登录的用户在视频播放界面"
--> "用户填写评论内容并提交表单"
--> "网页端将表单信息、视频id与用户id发送到后台"
--> "后台根据参数生成对应VideoComment类实例"
--> "调用服务层方法插入该条记录"
If "插入成功" then
    --> [Yes]"评论成功"
Else
    --> [No] "评论失败"
Endif
@enduml