@startuml
(*)  --> "管理员选择对应的Video"
--> "页面跳转到该Video的信息界面"
--> "管理员点击提交"
--> "服务器将请求参数注入，生成Video实体类"
--> "查询是否存在对应id的Video记录"
If "存在对应记录？" then
--> [Yes] "进行修改操作"
--> "修改完成"
--> "给出成功信息"
else
--> [No]"修改失败"
--> "给出失败信息"
Endif
@enduml