@startuml
(*)  --> "管理员上传视频"
--> "填写视频信息"
If "视频信息合法" then
    -right-> [Yes]"视频转码"
    If "转码成功" then
    --> [Yes] "将信息插入表单"
    --> "保存转码文件"
    -left-> "上传成功"
    -->(*)

    else
    --> "视频转码失败"
    --> "返回错误"
    Endif

Else
    --> [No]"填写视频信息"
Endif
@enduml