@startuml
(*)  -up-> "管理员上传视频"
-up-> "填写视频信息"
If "视频信息合法" then
    -up-> [Yes]"保存视频到临时文件夹"
    --> "判断视频大小是否过大"
    If "大于500M" then
        --> [Yes] "上传失败"
    Else
        -right-> "视频转码"
        If "转码成功" then
        --> [Yes] "根据转码后的视频生成\n视频存储路径与封面存储路径"
        --> "将信息插入表单"
        --> "保存转码文件"
        -down-> "上传成功"
        -->(*)

        else
        --> "视频转码失败"
        --> "返回错误"
        Endif
    Endif

Else
    -down-> [No]"填写视频信息"
Endif
@enduml